% Function: Plot_Channel.m @ CascadeCommunicator
% Author: Urs Hofmann
% Mail: hofmannu@biomed.ee.ethz.ch
% Date: 25.04.2019

% Description: Creates simple plot of laser trigger pattern

function Plot_Channel(cc, iLaser, laserColor)
	subplot(cc.nLasers, 1, iLaser)
	hold on
	plot(...
		[0, cc.tOn(1, iLaser), cc.tOn(1, iLaser), cc.tOff(1, iLaser), cc.tOff(1, iLaser)], ...
		[0, 0, 1, 1, 0], ...
		':',  'Color', laserColor);
	plot([cc.tFire(1, iLaser), cc.tFire(1, iLaser)], [0, 1], ...
		'Color', laserColor);
	fill(...
		[cc.tDac(1, iLaser), cc.tDac(1, iLaser), cc.tDac(1, iLaser) + cc.tAcquire, cc.tDac(1, iLaser) + cc.tAcquire], ...
		[0, 1, 1, 0], ...
		laserColor, 'EdgeColor', 'none', 'FaceAlpha', 0.25);
	hold off
end